### ISSUE TITLE
Other extensions buttons dissapear

### ISSUE THREAD

**Issue by NecroArt** [Sigizmund2012/pornhub#1]
Hello.
Thanks for g reat sloution.
I started to use this extension from yesterday and after several Chrome restart on my extension bar in Top Right corner only grey "P" button from this extention left.
I tried to disable and enable AgeRemover and other buttons appear again.

**Comment by Sigizmund2012** [comment]
Hello! I Don't know why this is happening. Just use Adblock Plus, this extension completely removes VK popup.
